public class SharepointConstants {
	public static String MDT_INSTANCE = 'Default';
    public static String AUTH_PATH = '/oauth2/v2.0/token';
    public static String AUTH_ENCODING_TYPE = 'UTF-8';
    public static String AUTH_CT_HEADER = 'Content-Tpe';
    public static String AUTH_CONTENT_TYPE = 'application/x-www-form-urlencoded';
    public static String AUTH_SCOPE = 'https://graph.microsoft.com/.default';
    public static String AUTH_GRANT_TYPE = 'client_credentials';
    public static String METHOD_POST = 'POST';
}